    name: Part 1 Workflow

    on:
      workflow_dispatch:
      push:
        tags:
          - checkMeP1*

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
